apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  http:
  - match:
    - uri:
        prefix: "/status/201"
    fault:
      abort:
        percentage:
          value: 50
        httpStatus: 500
    route:
    - destination:
        host: httpbin
        subset: v1
  
  # default non-delayed route
  - route:
    - destination:
        host: httpbin
        subset: v1